stages:
- name: 编译
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn install
- name: docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 10.1.8.15:5000/newlandtest/pms:1.0
      pushRemote: true
      registry: 10.1.8.15:5000
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
