apiVersion: v1
kind: Service
metadata:
  name: pms
spec:
  type: NodePort
  selector:
    app: pms-app
  ports:
  - name: http-pms
    port: 9777
    protocol: TCP
    targetPort: 9777 
    nodePort: 39777 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pms-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pms-app
        track: stable
    spec:
      containers:
      - name: pms-app
        image: 10.1.8.15:5000/newlandtest/pms:1.0
        imagePullPolicy: Always
        env:
        - name: GF_SERVER_ROOT_URL
          value: 'http://grafana.paas'
        ports:
        - containerPort: 9777 
